export { default as AddIcon } from './AddIcon'
export { default as AttachmentIcon } from './AttachmentIcon'
export { default as ChervonLeftIcon } from './ChervonLeftIcon'
export { default as CrossCircle2Icon } from './CrossCircle2Icon'
export { default as EditFilledIcon } from './EditFilledIcon'
export { default as ExportIcon } from './ExportIcon'
export { default as ImportIcon } from './ImportIcon'
export { default as PhoneIcon } from './PhoneIcon'
export { default as SettingsIcon } from './SettingsIcon'
export { default as TimeIcon } from './TimeIcon'
export { default as TrashIcon } from './TrashIcon'
export interface IIconName {
  name:
    | 'add'
    | 'attachment'
    | 'chervonleft'
    | 'crosscircle2'
    | 'editfilled'
    | 'export'
    | 'import'
    | 'phone'
    | 'settings'
    | 'time'
    | 'trash'
}

export type TIconName =
  | 'add'
  | 'attachment'
  | 'chervonleft'
  | 'crosscircle2'
  | 'editfilled'
  | 'export'
  | 'import'
  | 'phone'
  | 'settings'
  | 'time'
  | 'trash'
